# frozen_string_literal: true

{
  "Submission Date" => "Aug 11, 2022",
  "Approval Status" => nil,
  "First Name" => "Dilip",
  "Last Name" => "Chakma",
  "Organization / Affiliation" => "Indigenous Rights Advocacy Centre",
  "Date of Submission" => "Aug 11, 2022",
  "Email" => "indigenousrightsadvocacy@gmail.com",
  "Phone Number" => nil,
  "Is the documenter submitting this case factsheet as primary data?" => "Yes - (Primary data refers to data that are gathered directly from the victim/s, family/ies of the victim/s, member/s of the Indigenous Peoples that were affected.)",
  "Please provide information on source of data." => nil,
  "File Upload" => nil,
  "Provide relevant website/link" => nil,
  "As the documenter, I understand that Indigenous Peoples Rights International (IPRI) will record the information detailed in this case factsheet in its database. I am submitting this case factsheet with the following restrictions: (tick as preferred)" =>
   "The information in this case factsheet can be used by IPRI in understanding broad trends of criminalization, violence and impunity against Indigenous Peoples and can specifically refer to any of the details of this case.",
  "Subnational location" => "Madhya Pradesh",
  "Other Location Details (1)" => "Vidisha district",
  "Other Location Details (2)" => "Khatyapura village",
  "Time of Incident" => "10:00 PM",
  "Does the case involve individual/s or group/s of people (E.g., an entire village, members of an ethnic community, etc.)?" => "Individual - (Choose this category if the name/s of the victim/s is/are known)",
  "Name/s (Write Full Name)" => "Chain Singh",
  "Gender (Write M=Male; F=Female; Z= LGBTQIA+)(If more than one individual, indicate Gender of Individual according to the sequence of Name listed.)" => "M",
  "Dependent type (Write WD=with dependents; WOD=without dependents; ND= no data)(If more than one individual, indicate Dependent Type according to the sequence of Name listed.)" => "WD",
  "Please provide details of dependents. (E.g., children, partner, grandchildren etc.) (List details of dependents according to the sequence of Name listed.)" => "wives and chidlren",
  "Name/s of Indigenous Peoples’ group or Ethnic Identity/ies of victim/s (If more than on individual, list Indigenous Peoples’ group or Ethnic Identities according to the sequence of Name listed.)" => "Bhil",
  "Date of Birth (Write YYYY-MM-DD) (If more than one individual, list Date of Birth according to the sequence of Name listed.)" => nil,
  "Age Bracket (Write A= 0-14 years old; B= 15-24 years old; C= 25-59 years old; D= 60 years old and above) (If more than one individual, indicate Age Bracket according to sequence of Name listed.)" => "C",
  "Role/s of the Victim/s in the Community (The response in this field can be elder, healer or spiritual leader, community organizer, a vocal protester against human rights violations, etc.) (If more than one individual, write Role of the Victim in the Community according to the sequence of Name listed.) This information is meant to capture the victim/s’s involvement in the community and understand why s/he or they was/were the tar
 get of human rights violation and/or the impact of the human rights violation against him/her/them to the community or movement." =>
   nil,
  "Name/s of Indigenous Peoples’ group or Ethnic Identity/ies of peoples affected (If more than one Indigenous Peoples' group, list the name of each group.)" => nil,
  "Number of affected people" => nil,
  "Does the number of affected people refer to individuals" => nil,
  "Write the number of male from the total number of individuals affected:" => nil,
  "Write the number of female from the total number of individuals affected:" => nil,
  "Write the number of 0-14 years old from the total number of individuals affected:" => nil,
  "Write the number of 60 years old and above from the total number of individuals affected:" => nil,
  "Categories of Incidents of Human Rights Violations" => "Killing",
  "Why was/were the victim/s criminalized?" => nil,
  "Did the victim/s experience any form of harassment or intimidation prior to criminalization?" => nil,
  "If yes, please provide more information - Did the victim/s experience any form of harassment or intimidation prior to criminalization?" => nil,
  "What was/were the accusation/s or charge/s filed against the victim/s?" => nil,
  "What was/were the policy/ies or law/s or institutional justification/s used against the victim/s?" => nil,
  "Who put forward the accusation/s or charge/s against the victim/s?" => nil,
  "Was/were the accusation/s or charge/s against the victim legally or formally filed?" => nil,
  "If yes, where was the case/s filed? (e.g., regional court, military court, supreme court, etc.)" => nil,
  "Is there a decision on the legal or formal accusation/s or charge/s filed against the victim/s?" => nil,
  "Please provide more information - Is there a decision on the legal or formal accusation/s or charge/s filed against the victim/s?" => nil,
  "Is/Are the victim/s in prison or detention facility?" => nil,
  "If no, please provide more information on the current situation of the victim/s—Is/Are s/he/they in hiding? Released on bail? Awaiting court trial? On house arrest? etc." => nil,
  "If yes, please provide more information on their conditions or situation in the prison or detention facility—do they know where is the prison or detention facility located? Are they allowed visitors?" => nil,
  "Has there been any investigation/s on the incident of criminalization?" => nil,
  "If no, please elaborate on your response. (e.g. can you provide probable reasons on why there has been no investigation/s conducted? Or, is the case not yet publicly reported? Etc.)" => nil,
  "If yes, please provide additional information on the investigation, including relevant date/s and institutions/ office/s or representative/s involved, e.g., national human rights institutions, United Nations body, etc." => nil,
  "Why was/were the victim/s killed?" => "The victim went to forest to collect fire wood, along with seven other villagers, when they were fired upon by the forest officials",
  "How was the killing carried out?" => "The forest officials suddenly intercepted while the tribals were returning home with dry wood collected from the forest. The forest officials shot and killed Chain Singh on the spot and injured three others",
  "Did the victim/s experience any form of harassment or intimidation prior to the killing? E.g. death threats,  etc." => "No",
  "If yes, please provide more information." => nil,
  "Is/Are the alleged perpetrator/s known?" => nil,
  "(Tick as many as applicable)" => nil,
  "Was/Were there (a) legal case/s filed against the alleged perpetrators on behalf of the victim/s killed?" => "Yes",
  "If no, please elaborate on your response. (e.g. can you provide probable reasons on why there has been no legal case/s filed against the alleged perpetrators? Etc.)" => nil,
  "If yes, please provide further information: Where is/are the case/s filed? Who filed the case? E.g., victim, family of the victim, support organizations, etc.; any other details of the case/s filed, please share." => nil,
  "Has the State undertaken any action/s to address the incident of killing?" => "Yes",
  "If no, please elaborate on your response" => nil,
  "If yes, please provide more information on the action/s undertaken, including any relevant results." => "The State Government has suspended forest officials who were part of the team that killed the tribal and also ordered a judicial inquiry into the incident.",
  "Has there been any investigation/s on the incident of killing?" => "Yes",
  "If yes, please provide additional information on the investigation, including relevant date/s and institutions/ office/s or representative/s involved, e.g., national human rights institution, United Nations body, etc." => nil,
  "What was/were the human rights violation/s? (Tick as many as applicable.)" => nil,
  "Why did the victim/s suffer from the human rights violation/s?" => nil,
  "Was/Were there legal case/s filed against the alleged perpetrators on behalf of the victim/s?" => nil,
  "Has there been any investigation/s on the incident of other type of human right violation?" => nil,
  "How did the incident/s affect the victim/s and his/her/their family?" => "The families lost breadwinners.",
  "How did the incident/s affect the Indigenous Peoples group/s or community/ies and/or organization of the victim/s?" => "The incident shall instill fear among the tribals and disrupt their livelihood. They will be denied access to forest resources.",
  "Is/Are there any other advocacy and/or action/s undertaken" => "Yes",
  "Please elaborate on any action/s at national level and indicate the actor who initiated the action/s." => "Many human rights NGOs have raised voice and condemned the killing. IRAC has also submitted a complaint before the NHRC of India demanding judicial investigation, and justice.",
  "If no, please provide more information on actions undertaken." => nil,
  "Is the case related to (a) development project/s?" => "No",
  "If yes, do you have further details on the development project/s?" => nil,
  "Type of Development Project" => nil,
  "Name of development project/s" => nil,
  "Description of development project/s" => nil,
  "Source of information on development project" => nil,
  "Other relevant website/link" => nil,
  "Do you know if the development project/s has/have a parent company offshore?" => nil,
  "Country of parent company" => nil,
  "Description of parent company" => nil,
  "Source of information on parent company" => nil,
  "Is the case ongoing?" => "Yes",
  "If no, please provide more information" => nil,
  "Date of Incident" => nil,
  "Country of incident" => "India",
  "Please provide more information" => "The accused belong to South Lateri forest range in Vidisha district, Madhya Pradesh. They accused the victims of trying to smuggle woods from the forest.",
  "Contact Details" => "Email",
  "Indicate year of project's start of operation on the country where the incident of human rights violation happened" => nil,
  "Start Date of Incident" => "Aug 9, 2022",
  "Do you know if the development project/s is/are linked to any financial institution/s?" => nil,
  "Type of Funding source/s" => nil,
  "Description of Source/s of Funding" => nil,
  "Source of information on Funding Source" => nil
}
