# frozen_string_literal: true

class CreateDraftCaseDetails < ActiveRecord::Migration[7.2]
  def change
    create_table(:draft_case_details, id: :uuid) do |t|
      t.belongs_to(:case_import, null: false, foreign_key: true, type: :uuid)

      t.string(:organization_name)
      t.date(:submission_date)
      t.integer(:incident_start_year)
      t.integer(:incident_start_day)
      t.string(:incident_start_month)
      t.integer(:incident_end_year)
      t.integer(:incident_end_day)
      t.string(:incident_end_month)
      t.integer(:incident_hour)
      t.integer(:incident_minute)
      t.string(:time_period)

      t.string(:reference_number)
      t.boolean(:primary_data, null: false, default: false)
      t.string(:data_sharing)
      t.belongs_to(:country, foreign_key: true, type: :uuid)
      t.string(:subnational_location)
      t.string(:location_details_1)
      t.string(:location_details_2)
      t.text(:data_sources)

      t.text(:affected_total)
      t.text(:victim_details)
      t.boolean(:refer_to_individuals)
      t.integer(:male_total)
      t.integer(:female_total)

      t.text(:criminalization_details)
      t.string(:criminalization_experienced_harrassment_or_intimidation)
      t.text(:criminalization_harrassment_or_intimidation_details)
      t.text(:accusation_or_charges_details)
      t.text(:policies_or_laws_used)
      t.text(:accuser_details)
      t.string(:criminalization_case_filing_status)
      t.string(:criminalization_case_filing_details)
      t.string(:case_decision_status)
      t.string(:case_decision_details)
      t.string(:victims_in_detention)
      t.text(:victims_in_detention_details)
      t.string(:case_filing_against_perpetrator)
      t.text(:case_filing_against_perpetrator_details)
      t.string(:state_action_to_address_criminalization)
      t.text(:state_action_to_address_criminalization_details)
      t.string(:investigation_on_criminalization)
      t.text(:investigation_on_criminalization_details)
      t.text(:criminalization_impact_to_victim_details)
      t.text(:criminalization_impact_to_community_details)

      t.string(:documenter_id)
      t.string(:documenter_first_name)
      t.string(:documenter_last_name)
      t.string(:documenter_email)
      t.string(:documenter_phone_number)

      t.text(:impact_to_victim_details)
      t.text(:impact_to_community_details)
      t.text(:actions_taken_details)

      t.string(:project_name)
      t.text(:project_description)
      t.integer(:project_start_year)
      t.text(:project_website_sources)
      t.text(:development_project_category)

      t.text(:violation_details)
      t.string(:violation_alleged_perpetrators_known)
      t.text(:violation_alleged_perpetrator_details)
      t.string(:human_rights_violation_case_filing_status)
      t.text(:human_rights_violation_case_filing_details)
      t.string(:state_action_to_address_violation)
      t.string(:state_action_to_address_violation_details)
      t.string(:investigation_on_violation)
      t.text(:investigation_on_violation_details)
      t.string(:human_rights_violation_impact_to_victim_details)
      t.text(:human_rights_violation_impact_to_community_details)
      t.belongs_to(:age_bracket, foreign_key: true, type: :uuid)
      t.string(:full_name)
      t.string(:gender)
      t.string(:dependent_type)
      t.string(:ethnic_identity)
      t.string(:date_of_birth_month)
      t.integer(:date_of_birth_day)
      t.integer(:date_of_birth_year)
      t.text(:victim_role)
      t.text(:dependent_details)
      t.integer(:age_bracket_breakdown_0_12)
      t.integer(:age_bracket_breakdown_13_25)
      t.integer(:age_bracket_breakdown_26_35)
      t.integer(:age_bracket_breakdown_36_59)
      t.integer(:age_bracket_breakdown_60_plus)

      t.text(:killing_details)
      t.text(:killing_carried_out)
      t.string(:killing_experienced_harrassment_or_intimidation)
      t.text(:killing_harrassment_or_intimidation_details)
      t.string(:killing_alleged_perpetrators_known)
      t.text(:killing_alleged_perpetrator_details)
      t.string(:killing_case_filing_status)
      t.text(:state_action_to_address_killing)
      t.text(:state_action_to_address_killing_details)
      t.string(:investigation_on_killing)
      t.text(:investigation_on_killing_details)
    end
  end
end
